version: '3.8'

services:
  backend:
    build:
      context: ./operatingsystem
      dockerfile: Dockerfile
    container_name: operatingsystem
    ports:
      - "8083:8082" # L'moteur d l'backend kheddam f 8082 ldaakhel, w ghayban f 8083 3la berra
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.10.10.50:5432/kyntus_db
    restart: unless-stopped
    networks:
      - kyntus-network

  frontend:
    build:
      context: ./kyntus-os-frontend
      dockerfile: Dockerfile
    container_name: kyntus-os-frontend
    ports:
      - "3005:3000" # L'port 3000 mchdoud, 3tinah 3005 3la berra
    restart: unless-stopped
    networks:
      - kyntus-network

networks:
  kyntus-network:
    driver: bridge