version: '3.8'

services:
  # 1. La Base de Données (PostgreSQL)
  postgres-db:
    image: postgres:15-alpine
    container_name: kyntus_db
    restart: always
    environment:
      POSTGRES_USER: kyntus_user
      POSTGRES_PASSWORD: kyntus_password
      POSTGRES_DB: kyntus_os
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - kyntus-network

  # 2. Le Backend (Spring Boot 3la 8082)
  backend:
    build:
      context: ./operatingsystem # 🔥 THE FIX: Smiyt l'dossier s7i7a dyal Backend
      dockerfile: Dockerfile
    container_name: kyntus_backend
    restart: always
    ports:
      - "8082:8082" 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/kyntus_os
      - SPRING_DATASOURCE_USERNAME=kyntus_user
      - SPRING_DATASOURCE_PASSWORD=kyntus_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres-db
    networks:
      - kyntus-network

  # 3. Le Frontend (Next.js 3la 3030)
  frontend:
    build:
      context: ./kyntus-os-frontend # 🔥 THE FIX: Smiyt l'dossier s7i7a dyal Frontend
      dockerfile: Dockerfile
    container_name: kyntus_frontend
    restart: always
    ports:
      - "3030:3000"
    environment:
      # BDDEL "IP_DYAL_SERVEUR" b l'IP dyal l'serveur dyal charika
      - NEXT_PUBLIC_API_URL=http://IP_DYAL_SERVEUR:8082
    depends_on:
      - backend
    networks:
      - kyntus-network

networks:
  kyntus-network:
    driver: bridge

volumes:
  pgdata: