# ===============================
# DATABASE CONFIGURATION (Kyntus OS - APP 2)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/kyntus_db?reWriteBatchedInserts=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:waeloujdiastral481123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# HIBERNATE & JPA (RISK MANAGER MODE - READ/WRITE ONLY, NO SCHEMA CHANGES)
# ===============================
# CRITIQUE : none bach l App 2 m3emmerha t-creer wela t-supprimer une table f DB l asliya!
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER CONFIGURATION
# ===============================
# L App 1 khedama f 8082, donc had l App 2 ghandirouha f 8083 bach may-tra lina ta conflit
server.port=${SERVER_PORT:8083}

# ===============================
# LOGS & PERFORMANCE
# ===============================
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=ERROR

# Connection Pool (Optimise pour les traitements)
spring.datasource.hikari.maximum-pool-size=20

# ===============================
# HIBERNATE JSON MAPPER FIX (Matrix Decoder)
# ===============================
# ===============================
# HIBERNATE BATCH PROCESSING (THE V8 ENGINE - 10k BY 10k)
# ===============================
spring.jpa.properties.hibernate.jdbc.batch_size=10000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true